<?php

namespace Muhsenmaqsudi\Laratify\Tests;

use Illuminate\Support\Facades\View;
use Muhsenmaqsudi\Laratify\Providers\LaratifyServiceProvider;
use Orchestra\Testbench\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    public $hintPath = 'laratify::components';
    public $baseBgColor = 'bg-green-500';
    public $baseTextColor = 'text-white';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function renderView(string $view): string
    {
        return trim(View::file(__DIR__ . "/resources/views/{$view}.blade.php")->render());
    }

    protected function removeFileOrDir($path)
    {
        if (file_exists($path) && is_file($path)) {
            exec('rm '.$path);
        }

        if (file_exists($path) && is_dir($path)) {
            exec('rm  -r '.$path);
        }
    }

    protected function getPackageProviders($app)
    {
        return ['Muhsenmaqsudi\Laratify\Providers\LaratifyServiceProvider'];
    }
}
