<?php

namespace Muhsenmaqsudi\Laratify\Tests;

use Illuminate\Support\Facades\View;
use Muhsenmaqsudi\Laratify\Providers\LaratifyServiceProvider;
use Orchestra\Testbench\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    public $hintPath = 'laratify::components';
    public $baseBgColor = 'bg-green-500';
    public $baseTextColor = 'text-white';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadComponents();
    }

    private function loadComponents(): void
    {
        $service = new LaratifyServiceProvider($this->app);
        $service->boot();
    }

    public function renderView(string $view): string
    {
        return trim(View::file(__DIR__ . "/resources/views/{$view}.blade.php")->render());
    }
}
